In [2]:
import numpy as np

In [3]:
a = np.arange(1,6)
a2 = a[np.newaxis,:]
a3 = a2[np.newaxis,:]
a3

array([[[1, 2, 3, 4, 5]]])

In [4]:
a3.shape

(1, 1, 5)

In [5]:
a2.shape

(1, 5)

In [6]:
b = np.array([2,5,4,6,8,5,3,6,4])
b

array([2, 5, 4, 6, 8, 5, 3, 6, 4])

In [7]:
b.reshape(3,3)[0]

array([2, 5, 4])

In [8]:
c = np.zeros(10,dtype=int)
c

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
c = np.empty(10,dtype=int)
c

array([  0,   1,   0,   0, 864,   0, 768, 498,   0,   0])

In [10]:
d = np.arange(2,9,2)
d

array([2, 4, 6, 8])

In [11]:
e = np.linspace(1,10,num=10,dtype=int)
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [13]:
a3 = np.concatenate((x, y), axis=0)

In [14]:
a3.ndim

2

In [20]:
a3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
a3.reshape((2,3),order = 'F')

array([[1, 5, 4],
       [3, 2, 6]])

In [22]:
a3.reshape((2,3),order = 'C')

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
a3=np.expand_dims(e,axis=0)
a3

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [30]:
print([a3%2==0])

[array([[False,  True, False,  True, False,  True, False,  True, False,
         True]])]


In [9]:
a = np.array([[9, 10, 11, 12], [1, 2, 3, 4],[5, 6, 7, 8] ])
b = np.nonzero(a < 5)
b

(array([1, 1, 1, 1], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [13]:
lista =list(zip(a[0],a[1]))
for obj in lista :
    print(obj)

(9, 1)
(10, 2)
(11, 3)
(12, 4)


In [14]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

In [16]:
vs = np.vstack((a1,a2))
vs

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [23]:
hs = np.hstack((a1,a2))
hs

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [25]:
h = np.arange(1,25)
h

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [29]:
i = np.hsplit(h, (3,4))
i

[array([1, 2, 3]),
 array([4]),
 array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23, 24])]

In [34]:
j = np.random.default_rng(0)

In [35]:
np.save('filename', h)